#!/usr/bin/env python

import os
import shutil
import sys
import torch

from diffusers import StableDiffusionXLPipeline, DDPMScheduler

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import MODEL_CACHE, MODEL_ID, LOCAL_DIR

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = StableDiffusionXLPipeline.from_pretrained(
    MODEL_ID,
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.float16, 
    use_safetensors=True
)
